name: Deploy Auth Microservice

on:
  push:
    branches:
      - main
    paths:
      - 'auth-ms/**'
      - '.github/workflows/deploy-auth.yml'

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest

    env:
      STACK_NAME: auth-ms-stack
      TEMPLATE_FILE: infra/auth-ms.cloudformation.yml
      AWS_REGION: ${{ secrets.AWS_REGION }}
      IMAGE_URL: ${{ secrets.AUTH_MS_IMAGE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }} 

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --stack-name $STACK_NAME \
            --template-file $TEMPLATE_FILE \
            --capabilities CAPABILITY_NAMED_IAM \
            --region $AWS_REGION \
            --parameter-overrides \
              EnvName=dev \
              ImageUrl=${{ env.IMAGE_URL }} \
              ContainerPort=3001
